Update README.md. Fixed broken link
BenLorantfy/nestjs-zod pull request #86
Opened 2024-01-26 06:57 UTC by nikelborm

2024-11-05 03:12 UTC, nikelborm commented
So why was this PR closed? Could you please explain? The link is still broken...

![Screenshot From 2024-11-05 06-11-07](https://github.com/user-attachments/assets/095cc5e8-c955-4982-87c2-48afbeea2609)

2024-11-05 03:15 UTC, nikelborm commented
@BenLorantfy If you are the new repo owner could you please review and merge it?

2024-11-10 19:24 UTC, BenLorantfy requested changes

2024-11-10 19:24 UTC, BenLorantfy commented on README.md
> +- [zod-nestjs](https://github.com/anatine/zod-plugins/blob/main/packages/zod-nestjs/README.md) and [zod-openapi](https://github.com/anatine/zod-plugins/tree/main/libs/zod-openapi)
```suggestion
- [zod-nestjs](https://github.com/anatine/zod-plugins/blob/main/packages/zod-nestjs/README.md) and [zod-openapi](https://github.com/anatine/zod-plugins/tree/main/packages/zod-openapi)  
```

2024-11-10 19:27 UTC, BenLorantfy approved these changes

2024-11-10 19:27 UTC, merged